#!/usr/bin/env python3
# /// script
# dependencies = [
#   "pyyaml",
# ]
# requires-python = ">=3.9,<3.14"
# ///
"""
kb-lint — vault health check (read-only).
Usage: uv run .agents/skills/kb-lint/lint.py
Writes: views/lint-report.md, wiki/overview.md
Appends: wiki/log.md

Split layout: core.py (constants/helpers), checks.py (check_* functions),
lint.py (report writers + main). Tests import everything from lint.
"""
from __future__ import annotations

import datetime
import json
import os
import re
import sys
from pathlib import Path

import yaml  # noqa: F401  (re-export for any direct users)

from core import *      # noqa: F401,F403
from checks import *    # noqa: F401,F403

# ── Output writers ────────────────────────────────────────────────────────

_SECTIONS = [
    ("orphans",             "## Orphans"),
    ("broken_links",        "## Broken links"),
    ("schema_violations",   "## Schema violations"),
    ("stale_pages",         "## Stale pages"),
    ("contradictions",      "## Contradictions"),
    ("bloated_pages",       "## Bloated pages"),
    ("raw_drift",           "## Raw drift"),
    ("log_rotation",        "## Log rotation needed"),
    ("edges_rotation",      "## Edges rotation needed"),
    ("graph_invariants",    "## Graph invariants"),
    ("stale_action_items",  "## Stale action items"),
    ("unprocessed_journal", "## Unprocessed journal entries"),
    ("duplicate_stubs",     "## Duplicate stubs (promotion leftovers)"),
    ("decision_date",       "## Decisions missing date"),
]


def write_lint_report(findings: list[dict], vault: Path) -> None:
    by_check: dict[str, list[dict]] = {}
    for f in findings:
        by_check.setdefault(f["check"], []).append(f)

    views_dir = vault / "views"
    views_dir.mkdir(exist_ok=True)
    lines = [
        "# views/lint-report.md — kb-lint findings\n",
        f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
        f"Total findings: {len(findings)}\n",
    ]

    for check_key, header in _SECTIONS:
        lines.append(f"\n{header}\n")
        section_findings = by_check.get(check_key, [])
        if not section_findings:
            lines.append("_No issues._\n")
        else:
            for f in section_findings:
                lines.append(f"- `{f['path']}` — {f['message']}\n")

    (views_dir / "lint-report.md").write_text("".join(lines), encoding="utf-8")


def write_overview(
    pages: list[dict],
    vault: Path,
    state_path: Path,
    today: datetime.date,
) -> None:
    # Count pages by type
    type_counts: dict[str, int] = {t: 0 for t in sorted(NODE_TYPES)}
    for p in pages:
        if p["type"] in type_counts:
            type_counts[p["type"]] += 1

    # Last ingest per channel from state file
    last_ingest: dict[str, str] = {}
    if state_path.exists():
        try:
            state = json.loads(state_path.read_text(encoding="utf-8"))
            for raw_path, meta in state.items():
                parts = raw_path.split("/")
                channel = parts[1] if len(parts) > 1 else "unknown"
                ts = meta.get("ts", "")
                if ts > last_ingest.get(channel, ""):
                    last_ingest[channel] = ts[:10]
        except (json.JSONDecodeError, ValueError):
            pass

    channels = ["journal", "meetings", "emails", "chats", "clippings", "docs"]

    # Open action items
    open_items = sum(p["body"].count("- [ ]") for p in pages)

    # Top 5 stale (oldest last_verified or modified)
    dated: list[tuple[str, str]] = []
    for p in pages:
        if p["fm"] is None:
            continue
        d = str(p["fm"].get("last_verified") or p["fm"].get("modified") or "")
        if d:
            dated.append((d, str(p["path"])))
    top5_stale = sorted(dated)[:5]

    # Edges depth
    edges_path = vault / "wiki" / "_inbox" / "edges.md"
    edge_count = 0
    if edges_path.exists():
        text = edges_path.read_text(encoding="utf-8", errors="replace")
        edge_count = sum(1 for line in text.splitlines() if line.startswith("- ("))

    lines = [
        "# wiki/overview.md — Synthesis dashboard\n\n",
        "Regenerated by /kb-lint at the end of every lint pass. Do not edit by hand.\n\n",
        "## Page counts\n\n",
        "| Type | Count |\n|---|---|\n",
    ]
    for t in sorted(NODE_TYPES):
        lines.append(f"| {t} | {type_counts.get(t, 0)} |\n")

    lines.append(f"\n## Open action items\n\n{open_items} open action items across wiki/.\n\n")
    lines.append("## Last ingest per channel\n\n| Channel | Last ingest |\n|---|---|\n")
    for ch in channels:
        lines.append(f"| {ch} | {last_ingest.get(ch, '—')} |\n")

    lines.append("\n## Top 5 stale pages\n\n")
    if top5_stale:
        for date_str, path in top5_stale:
            lines.append(f"- `{path}` (last verified/modified: {date_str})\n")
    else:
        lines.append("None.\n")

    lines.append(f"\n## _inbox/edges.md depth\n\n{edge_count} entries.\n")

    (vault / "wiki").mkdir(exist_ok=True)
    (vault / "wiki" / "overview.md").write_text("".join(lines), encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────

def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="kb-lint vault health check")
    parser.add_argument("--today", help="Override today's date (YYYY-MM-DD) for testing")
    args = parser.parse_args()

    today = (datetime.date.fromisoformat(args.today)
             if args.today else datetime.date.today())

    vault = find_vault_root(Path(__file__).resolve().parent)
    wiki_dir = vault / "wiki"
    state_path = vault / "raw" / ".ingest-state.json"
    log_path = vault / "wiki" / "log.md"
    edges_path = vault / "wiki" / "_inbox" / "edges.md"

    pages = collect_pages(wiki_dir)
    link_graph = build_link_graph(pages)

    all_findings: list[dict] = []
    all_findings += check_orphans(pages, link_graph)
    all_findings += check_broken_links(pages, vault)
    all_findings += check_schema_violations(pages)
    all_findings += check_stale_last_verified(pages, today)
    all_findings += check_contradictions(pages)
    all_findings += check_bloated_pages(pages)
    all_findings += check_raw_drift(vault, state_path)
    all_findings += check_log_rotation(log_path)
    all_findings += check_edges_rotation(edges_path)
    all_findings += check_decision_sources(pages)
    all_findings += check_person_works_at(pages)
    all_findings += check_stale_action_items(pages, today)
    all_findings += check_unprocessed_journal(vault, state_path, today)
    all_findings += check_duplicate_stubs(wiki_dir)
    all_findings += check_decision_date(pages)

    write_lint_report(all_findings, vault)
    write_overview(pages, vault, state_path, today)

    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    check_count = 15
    log_line = (f"\n## [{ts}] kb-lint | "
                f"{len(all_findings)} issues found across {check_count} checks\n")
    with log_path.open("a", encoding="utf-8") as fh:
        fh.write(log_line)

    print(f"lint: {len(all_findings)} issues across {check_count} checks")
    print("  views/lint-report.md written")
    print("  wiki/overview.md written")

    by_check: dict[str, int] = {}
    for finding in all_findings:
        by_check[finding["check"]] = by_check.get(finding["check"], 0) + 1
    for check_key, header in _SECTIONS:
        count = by_check.get(check_key, 0)
        if count:
            print(f"  {header.lstrip('#').strip()}: {count}")


if __name__ == "__main__":
    main()
