#!/usr/bin/env python3
# /// script
# dependencies = []
# requires-python = ">=3.9,<3.14"
# ///
"""
kb-status — vault dashboard. Reads cached wiki/overview.md (regenerated by /kb-lint).

Usage:
  uv run .agents/skills/kb-status/status.py

Read-only. No writes. Stdout only.
Vault root auto-detected (walks up for CLAUDE.md).
"""
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from common import find_vault_root  # noqa: E402


_TABLE_ROW = re.compile(r"^\|\s*(?P<key>[^|]+?)\s*\|\s*(?P<val>[^|]+?)\s*\|\s*$")


def _section_text(text: str, header: str) -> str | None:
    """Return the slice between `## <header>` and the next `## ` (or EOF)."""
    pat = re.compile(rf"^## {re.escape(header)}\s*$", re.MULTILINE)
    m = pat.search(text)
    if not m:
        return None
    after = text[m.end():]
    nxt = re.search(r"^## ", after, re.MULTILINE)
    return after[: nxt.start()] if nxt else after


def _iter_table_rows(text: str, header: str, skip_keys: set[str]):
    section = _section_text(text, header)
    if section is None:
        return
    for line in section.splitlines():
        m = _TABLE_ROW.match(line)
        if not m:
            continue
        k, v = m.group("key").strip(), m.group("val").strip()
        if k.lower() in skip_keys:
            continue
        yield k, v


def parse_overview_page_counts(text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for k, v in _iter_table_rows(text, "Page counts", {"type", "---"}):
        try:
            out[k] = int(v)
        except ValueError:
            continue
    return out


def parse_overview_last_ingest(text: str) -> dict[str, str]:
    return {
        k: v for k, v in _iter_table_rows(text, "Last ingest per channel", {"channel", "---"})
    }


def count_inbox(raw_dir: Path) -> dict[str, int]:
    inbox = raw_dir / "inbox"
    if not inbox.is_dir():
        return {}
    out: dict[str, int] = {}
    for sub in sorted(inbox.iterdir()):
        if not sub.is_dir():
            continue
        out[sub.name] = sum(1 for _ in sub.glob("*.md"))
    return out


def count_quarantine(raw_dir: Path) -> int:
    # Each quarantined incident has a source file + sibling `.error.md` (CLAUDE.md
    # convention). Count incidents (source files), not total files.
    q = raw_dir / "quarantine"
    if not q.is_dir():
        return 0
    return sum(1 for p in q.iterdir() if p.is_file() and not p.name.endswith(".error.md"))


_EDGE_BULLET = re.compile(r'^- \(\S+,\s+\S+,\s+\S+,\s+[\d.]+,\s+".*"\)\s*$')


def count_edge_proposals(edges_path: Path) -> int:
    if not edges_path.is_file():
        return 0
    return sum(
        1 for line in edges_path.read_text(encoding="utf-8", errors="replace").splitlines()
        if _EDGE_BULLET.match(line)
    )


_LOG_ENTRY = re.compile(r"^## \[")


def count_log_entries(log_path: Path) -> int:
    if not log_path.is_file():
        return 0
    return sum(
        1 for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines()
        if _LOG_ENTRY.match(line)
    )


def count_threads(threads_dir: Path) -> int:
    if not threads_dir.is_dir():
        return 0
    return sum(1 for _ in threads_dir.glob("*.md"))


def format_dashboard(
    now: datetime,
    overview_age_hours: float | None,
    page_counts: dict[str, int],
    last_ingest: dict[str, str],
    inbox: dict[str, int],
    quarantine: int,
    edges: int,
    log_entries: int,
    threads: int,
) -> str:
    ts = now.strftime("%Y-%m-%d %H:%M")
    page_order = ["Person", "Org", "Project", "Topic", "Decision", "Meeting", "Source", "Artifact", "Event"]
    # When any counts exist, render the full type roster (missing types as 0).
    page_str = (
        "  ".join(f"{t}={page_counts.get(t, 0)}" for t in page_order)
        if page_counts else "(none)"
    )
    inbox_order = ["journal", "meetings", "emails", "chats", "clippings", "docs"]
    inbox_str = "  ".join(
        f"{c}={inbox.get(c, 0)}" for c in inbox_order if c in inbox
    ) or "(none)"
    ingest_str = "  ".join(
        f"{c}={d}" for c, d in last_ingest.items()
    ) or "(none)"
    age_str = (
        f"{overview_age_hours:.1f}h old  (regenerated by /kb-lint)"
        if overview_age_hours is not None else "missing — run /kb-lint"
    )
    lines = [
        f"work-brain status — {ts}",
        "",
        f"Overview:     {age_str}",
        f"Pages:        {page_str}",
        f"Inbox:        {inbox_str}",
        f"Quarantine:   {quarantine} files",
        f"Edges inbox:  {edges} proposals  (rotation threshold: 500)",
        f"Log:          {log_entries} entries  (rotation threshold: 1000)",
        f"Last ingest:  {ingest_str}",
        f"Open threads: {threads}",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    vault = find_vault_root(Path(__file__).parent)
    overview_text = ""
    overview = vault / "wiki" / "overview.md"
    overview_age_hours = None
    if overview.is_file():
        overview_text = overview.read_text(encoding="utf-8", errors="replace")
        overview_age_hours = (
            datetime.now(timezone.utc).timestamp() - overview.stat().st_mtime
        ) / 3600
    page_counts = parse_overview_page_counts(overview_text)
    last_ingest = parse_overview_last_ingest(overview_text)
    inbox = count_inbox(vault / "raw")
    quarantine = count_quarantine(vault / "raw")
    edges = count_edge_proposals(vault / "wiki" / "_inbox" / "edges.md")
    log_entries = count_log_entries(vault / "wiki" / "log.md")
    threads = count_threads(vault / "wiki" / "threads")
    print(format_dashboard(
        now=datetime.now(timezone.utc),
        overview_age_hours=overview_age_hours,
        page_counts=page_counts,
        last_ingest=last_ingest,
        inbox=inbox,
        quarantine=quarantine,
        edges=edges,
        log_entries=log_entries,
        threads=threads,
    ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
